#!/bin/bash

choice=$(echo -e "󰐥  Power Off\n  Reboot\n󰜉  Lock\n󰤄  Suspend\n󰗽  Logout" | fuzzel --dmenu --lines 5)

case "$choice" in
  *Power\ Off) systemctl poweroff ;;
  *Reboot) systemctl reboot ;;
  *Lock) hyprlock ;;
  *Suspend) systemctl suspend ;;
  *Logout) hyprctl dispatch exit ;;
esac
