version = 3
final_space = true

[palette]
  blue = '#89B4FA'
  flamingo = '#F2CDCD'
  green = '#A6E3A1'
  lavender = '#B4BEFE'
  marron = '#EBA0AC'
  mauve = '#CBA6F7'
  os = '#ACB0BE'
  peach = '#FAB387'
  pink = '#F5C2E7'
  red = '#F38BA8'
  rosewater = '#F5E0DC'
  sapphire = '#74C7EC'
  sky = '#89DCEB'
  teal = '#94E2D5'
  yellow = '#F9E2AF'

[secondary_prompt]
  template = ''
  foreground = 'p:rosewater'
  background = 'transparent'

[transient_prompt]
  template = ''
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:rosewater{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'p:sapphire'
    background = 'transparent'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }} '
    foreground = 'p:mauve'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ .HEAD }}'
    foreground = 'p:lavender'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    template = '{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}'
    foreground = 'p:blue'
    background = 'transparent'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:yellow{{ end }}', '{{ if gt .Ahead 0 }}p:green{{ end }}', '{{ if gt .Behind 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = '{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}'
    foreground = 'p:teal'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = '{{if .Working.Changed }}  {{ .Working.String }}{{ end }}'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 3000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ''
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:rosewater{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
